### ISSUE TITLE
Incorrect pins in schematic of APDS-9008

### ISSUE THREAD

**Issue by wbadry** [WorldFamousElectronics/PulseSensorAmped_Hardware#2]
Hello,
I believe there is a mistake in the schematic regarding **APDS-9008 pin connection**

Used pins are supposed to be 1,4 and 6
![alt text](https://i.ibb.co/rx3bWfW/2019-03-22-16-53-26.png)

On schematic, it is 1,3 and 4
![alt text](https://i.ibb.co/6NVN0Fh/2019-03-22-16-58-09.png)

**Comment by biomurph** [comment]
Actually, it is correct-ish.
If you look at the footprint for the part, I am omitting the component pins 2 and 5, since they are unused in the circuit. This makes the piece a little easier for my CM to produce, and alot easier if someone wants to make their own.

**Comment by wbadry** [comment]
> 
> 
> Actually, it is correct-ish.
> If you look at the footprint for the part, I am omitting the component pins 2 and 5, since they are unused in the circuit. This makes the piece a little easier for my CM to produce, and alot easier if someone wants to make their own.

it is not about omitting the **NC pins** which I agree with. It is about the pin number that is incorrect in the schematic leading to definitely wrong connection diagram. 

|  Pins (APDS-9008) | Vcc | GND | Iout |
|:-----------------:|:---:|:---:|:----:|
|   Schematic       |  1  |  3  |   4  |
|     APDS-9008     |  1  |  4  |   6  |

The datasheet can be fetched from [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi25r3eppbhAhVOyoUKHRgsD40QFjAAegQIABAC&url=https%3A%2F%2Fwww.mouser.com%2Fds%2F2%2F678%2FV02-1169EN0-908795.pdf&usg=AOvVaw3w58wjtSgzso24dHOanjjH). You did a great job. It is just a note for others to know, otherwise, this chip will be not work at all with current schematic. You may ofcourse correct me if mistaken.

**Comment by biomurph** [comment]
Ah yes, if you follow my modified schematic it will confuse. But it happens to be connected to my footprint...
Said it was open source, didn't say it was gonna be easy. ;)
