### ISSUE TITLE
PDF of schematic?

### ISSUE THREAD

**Issue by RobotZwrrl** [WorldFamousElectronics/PulseSensorAmped_Hardware#3]
Hi there! Long time fan of the pulse sensor. I was looking at the schematic [here](https://cdn.shopify.com/s/files/1/0100/6632/files/PulseSensorAmpd_-_Schematic.pdf?1862089645030619491) posted [on this page](https://pulsesensor.com/pages/open-hardware), but it wasn't clear to me if this is the newest schematic with the changes - or not. 

Can you confirm if that is the most up to date schematic? If not... would it be possible to post a pdf of the schematic from the design files in this repository?

Hope you don't mind this request. 
Thank you!

**Comment by biomurph** [comment]
@RobotGrrl 
Hey, I think we met once at an OSHWA Summit? 
Yes, the schematic that you link to is basically up-to-date. One thing that you should note is that the resistor R1 needs to be tuned to the brightness of the LED. The LED we use has different brightness based on BIN code on the reel. Something to keep in mind if you're trying to make one yourself.
