### ISSUE TITLE
line 1, column 1: Start tag expected.

### ISSUE THREAD

**Issue by shridharnator** [WorldFamousElectronics/PulseSensorAmped_Hardware#4]
This is the error I get when I try to open the schematic. Please help.
![Screenshot (408)](https://user-images.githubusercontent.com/32407571/105960657-8d361680-60a3-11eb-8f8f-2774734d4fe0.png)
 in EAGLE.

**Comment by biomurph** [comment]
@shridharnator
The designs were made with Design Spark.
Please use that software 
Please read the Read Me file.
